version: '3.8'
services:
  backend: 
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python manage.py runserver 0.0.0.0:8000'
    ports:
      - 9000:8000
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
        PIKA_URL : ${PIKA_URL}
        USER_POSTGRES: ${USER_POSTGRES}
        PASS_POSTGRES: ${PASS_POSTGRES}
  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python consumer.py'
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: ${USER_POSTGRES}
      POSTGRES_PASSWORD: ${PASS_POSTGRES}
      POSTGRES_DB: admin_django
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - 9001:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d admin_django -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5