version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python main.py'
    ports:
      - 5001:5000
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
        PIKA_URL : ${PIKA_URL}
        USER_POSTGRES: ${USER_POSTGRES}
        PASS_POSTGRES: ${PASS_POSTGRES}
  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python consumer.py'
    depends_on:
      - db

  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: ${USER_POSTGRES}
      MYSQL_PASSWORD: ${PASS_POSTGRES}
      MYSQL_ROOT_PASSWORD: ${PASS_POSTGRES}
    volumes:
      - ./dbdata:/var/lib/mysql
    ports:
      - 33067:3306