"""empty message

Revision ID: a842293df915
Revises: 3b3fc216ebc3
Create Date: 2021-12-14 23:07:36.425317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a842293df915'
down_revision = '3b3fc216ebc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_product_unique', 'product_user', ['user_id', 'product_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_product_unique', 'product_user', type_='unique')
    # ### end Alembic commands ###
